<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class AtsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('supplier_identification_types')->insert([
            ['code' => 1, 'name' => 'PERSONA NATURAL', 'created_at' => Carbon::now()],
            ['code' => 2, 'name' => 'SOCIEDAD', 'created_at' => Carbon::now()],
        ]);

        DB::table('support_vouchers')->insert([
            ['code' => 1, 'name' => 'CRÉDITO TRIBUTARIO PARA DECLARACIÓN DE IVA (SERVICIOS Y BIENES DISTINTOS DE INVENTARIOS Y ACTIVOS FIJOS)', 'created_at' => Carbon::now()],
            ['code' => 2, 'name' => 'COSTO O GASTO PARA DECLARACIÓN DE IR (SERVICIOS Y BIENES DISTINTOS DE INVENTARIOS Y ACTIVOS FIJOS)', 'created_at' => Carbon::now()],
            ['code' => 3, 'name' => 'ACTIVO FIJO - CRÉDITO TRIBUTARIO PARA DECLARACIÓN DE IVA', 'created_at' => Carbon::now()],
            ['code' => 4, 'name' => 'ACTIVO FIJO - COSTO O GASTO PARA DECLARACIÓN DE IR', 'created_at' => Carbon::now()],
            ['code' => 5, 'name' => 'LIQUIDACIÓN GASTOS DE VIAJE, HOSPEDAJE Y ALIMENTACIÓN GASTOS IR (A NOMBRE DE EMPLEADOS Y NO DE LA EMPRESA)', 'created_at' => Carbon::now()],
            ['code' => 6, 'name' => 'INVENTARIO - CRÉDITO TRIBUTARIO PARA DECLARACIÓN DE IVA', 'created_at' => Carbon::now()],
            ['code' => 7, 'name' => 'INVENTARIO - COSTO O GASTO PARA DECLARACIÓN DE IR', 'created_at' => Carbon::now()],
            ['code' => 8, 'name' => 'VALOR PAGADO PARA SOLICITAR REEMBOLSO DE GASTO (INTERMEDIARIO)', 'created_at' => Carbon::now()],
            ['code' => 9, 'name' => 'REEMBOLSO POR SINIESTROS', 'created_at' => Carbon::now()],
            ['code' => 10, 'name' => 'DISTRIBUCIÓN DE DIVIDENDOS, BENEFICIOS O UTILIDADES', 'created_at' => Carbon::now()],
            ['code' => 11, 'name' => 'CONVENIOS DE DÉBITO O RECAUDACIÓN PARA IFI´S', 'created_at' => Carbon::now()],
            ['code' => 12, 'name' => 'IMPUESTOS Y RETENCIONES PRESUNTIVOS', 'created_at' => Carbon::now()],
            ['code' => 13, 'name' => 'VALORES RECONOCIDOS POR ENTIDADES DEL SECTOR PÚBLICO A FAVOR DE SUJETOS PASIVOS', 'created_at' => Carbon::now()],
            ['code' => 14, 'name' => 'VALORES FACTURADOS POR SOCIOS A OPERADORAS DE TRANSPORTE (QUE NO CONSTITUYEN GASTO DE DICHA OPERADORA)', 'created_at' => Carbon::now()],
            ['code' => 0, 'name' => 'CASOS ESPECIALES CUYO SUSTENTO NO APLICA EN LAS OPCIONES ANTERIORES', 'created_at' => Carbon::now()],
        ]);

        DB::table('payment_types')->insert([
            ['code' => 1, 'name' => 'PAGO A RESIDENTE / ESTABLECIMIENTO PERMANENTE', 'created_at' => Carbon::now()],
            ['code' => 2, 'name' => 'PAGO A NO RESIDENTE', 'created_at' => Carbon::now()],
        ]);

        DB::table('foreign_fiscal_regime_types')->insert([
            ['code' => 1, 'name' => 'RÉGIMEN GENERAL', 'created_at' => Carbon::now()],
            ['code' => 2, 'name' => 'PARAÍSO FISCAL', 'created_at' => Carbon::now()],
            ['code' => 3, 'name' => 'RÉGIMEN FISCAL PREFERENTE O JURISDICCIÓN DE MENOR IMPOSICIÓN', 'created_at' => Carbon::now()],
        ]);

        DB::table('countries')->insert([
            ['code' => 16, 'name' => 'AMERICAN SAMOA', 'tax_haven_code' => 75, 'tax_haven_name' => 'SAMOA AMERICANA (Territorio no autónomo de los EEUU)', 'created_at' => Carbon::now()],
            ['code' => 74, 'name' => 'BOUVET ISLAND', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 101, 'name' => 'ARGENTINA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 102, 'name' => 'BOLIVIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 103, 'name' => 'BRASIL', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 104, 'name' => 'CANADA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 105, 'name' => 'COLOMBIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 106, 'name' => 'COSTA RICA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 107, 'name' => 'CUBA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 108, 'name' => 'CHILE', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 109, 'name' => 'ANGUILA', 'tax_haven_code' => 1, 'tax_haven_name' => 'ANGUILA (Territorio no autónomo del Reino Unido)', 'created_at' => Carbon::now()],
            ['code' => 110, 'name' => 'ESTADOS UNIDOS', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 111, 'name' => 'GUATEMALA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 112, 'name' => 'HAITI', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 113, 'name' => 'HONDURAS', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 114, 'name' => 'JAMAICA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 115, 'name' => 'MALVINAS  ISLAS', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 116, 'name' => 'MEXICO', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 117, 'name' => 'NICARAGUA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 118, 'name' => 'PANAMA', 'tax_haven_code' => 68, 'tax_haven_name' => 'REPÚBLICA DE PANAMÁ (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 119, 'name' => 'PARAGUAY', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 120, 'name' => 'PERU', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 121, 'name' => 'PUERTO RICO', 'tax_haven_code' => 17, 'tax_haven_name' => 'ESTADO LIBRE ASOCIADO DE PUERTO RICO (Estado asociado a los EEUU)', 'created_at' => Carbon::now()],
            ['code' => 122, 'name' => 'REPUBLICA DOMINICANA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 123, 'name' => 'EL SALVADOR', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 124, 'name' => 'TRINIDAD Y TOBAGO', 'tax_haven_code' => 70, 'tax_haven_name' => 'REPÚBLICA DE TRINIDAD Y TOBAGO', 'created_at' => Carbon::now()],
            ['code' => 125, 'name' => 'URUGUAY', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 126, 'name' => 'VENEZUELA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 127, 'name' => 'CURAZAO', 'tax_haven_code' => 13, 'tax_haven_name' => 'CURAZAO', 'created_at' => Carbon::now()],
            ['code' => 129, 'name' => 'BAHAMAS', 'tax_haven_code' => 12, 'tax_haven_name' => 'COMUNIDAD DE LAS BAHAMAS (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 130, 'name' => 'BARBADOS', 'tax_haven_code' => 5, 'tax_haven_name' => 'BARBADOS (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 131, 'name' => 'GRANADA', 'tax_haven_code' => 14, 'tax_haven_name' => 'ESTADO ASOCIADO DE GRANADA (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 132, 'name' => 'GUYANA', 'tax_haven_code' => 56, 'tax_haven_name' => 'REPÚBLICA COOPERATIVA DE GUYANA (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 133, 'name' => 'SURINAM', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 134, 'name' => 'ANTIGUA Y BARBUDA', 'tax_haven_code' => 2, 'tax_haven_name' => 'ANTIGUA Y BARBUDA (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 135, 'name' => 'BELICE', 'tax_haven_code' => 6, 'tax_haven_name' => 'BELICE (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 136, 'name' => 'DOMINICA', 'tax_haven_code' => 42, 'tax_haven_name' => 'MANCOMUNIDAD DE DOMINICA (Estado asociado)', 'created_at' => Carbon::now()],
            ['code' => 137, 'name' => 'SAN CRISTOBAL Y NEVIS', 'tax_haven_code' => 19, 'tax_haven_name' => 'FEDERACIÓN DE SAN CRISTÓBAL (Islas Saint Kitts and Nevis: independientes)', 'created_at' => Carbon::now()],
            ['code' => 138, 'name' => 'SANTA LUCIA', 'tax_haven_code' => 79, 'tax_haven_name' => 'SANTA LUCÍA', 'created_at' => Carbon::now()],
            ['code' => 139, 'name' => 'SAN VICENTE Y LAS GRANAD.', 'tax_haven_code' => 77, 'tax_haven_name' => 'SAN VICENTE Y LAS GRANADINAS (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 141, 'name' => 'ARUBA', 'tax_haven_code' => 4, 'tax_haven_name' => 'ARUBA', 'created_at' => Carbon::now()],
            ['code' => 142, 'name' => 'BERMUDA', 'tax_haven_code' => 7, 'tax_haven_name' => 'BERMUDAS (Territorio no autónomo del Reino Unido)', 'created_at' => Carbon::now()],
            ['code' => 143, 'name' => 'GUADALUPE', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 144, 'name' => 'GUYANA FRANCESA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 145, 'name' => 'ISLAS CAIMAN', 'tax_haven_code' => 25, 'tax_haven_name' => 'ISLAS CAIMÁN (Territorio no autónomo del Reino Unido)', 'created_at' => Carbon::now()],
            ['code' => 146, 'name' => 'ISLAS VIRGENES (BRITANICAS)', 'tax_haven_code' => 36, 'tax_haven_name' => 'ISLAS VÍRGENES BRITÁNICAS (Territorio no autónomo del Reino Unido)', 'created_at' => Carbon::now()],
            ['code' => 147, 'name' => 'JOHNSTON ISLA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 148, 'name' => 'MARTINICA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 149, 'name' => 'MONTSERRAT ISLA', 'tax_haven_code' => 43, 'tax_haven_name' => 'MONTSERRAT (Territorio no autónomo del Reino Unido)', 'created_at' => Carbon::now()],
            ['code' => 151, 'name' => 'TURCAS  Y CAICOS ISLAS', 'tax_haven_code' => 35, 'tax_haven_name' => 'ISLAS TURKAS E ISLAS CAICOS (Territorio no autónomo del Reino Unido)', 'created_at' => Carbon::now()],
            ['code' => 152, 'name' => 'VIRGENES,ISLAS(NORT.AMER.)', 'tax_haven_code' => 37, 'tax_haven_name' => 'ISLAS VÍRGENES DE ESTADOS UNIDOS DE AMÉRICA', 'created_at' => Carbon::now()],
            ['code' => 201, 'name' => 'ALBANIA', 'tax_haven_code' => 57, 'tax_haven_name' => 'REPÚBLICA DE ALBANIA', 'created_at' => Carbon::now()],
            ['code' => 202, 'name' => 'ALEMANIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 203, 'name' => 'AUSTRIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 204, 'name' => 'BELGICA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 205, 'name' => 'BULGARIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 207, 'name' => 'ALBORAN Y PEREJIL', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 208, 'name' => 'DINAMARCA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 209, 'name' => 'ESPAÑA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 211, 'name' => 'FRANCIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 212, 'name' => 'FINLANDIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 213, 'name' => 'REINO UNIDO', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 214, 'name' => 'GRECIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 215, 'name' => 'PAISES BAJOS (HOLANDA)', 'tax_haven_code' => 8, 'tax_haven_name' => 'BONAIRE, SABA Y SAN EUSTAQUIO', 'created_at' => Carbon::now()],
            ['code' => 216, 'name' => 'HUNGRIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 217, 'name' => 'IRLANDA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 218, 'name' => 'ISLANDIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 219, 'name' => 'ITALIA', 'tax_haven_code' => 10, 'tax_haven_name' => 'CAMPIONE D\'ITALIA (Comune di Campioned\'Italia)', 'created_at' => Carbon::now()],
            ['code' => 220, 'name' => 'LUXEMBURGO', 'tax_haven_code' => 20, 'tax_haven_name' => 'GRAN DUCADO DE LUXEMBURGO', 'created_at' => Carbon::now()],
            ['code' => 221, 'name' => 'MALTA', 'tax_haven_code' => 65, 'tax_haven_name' => 'REPÚBLICA DE MALTA (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 222, 'name' => 'NORUEGA', 'tax_haven_code' => 3, 'tax_haven_name' => 'ARCHIPIÉLAGO DE SVALBARD', 'created_at' => Carbon::now()],
            ['code' => 223, 'name' => 'POLONIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 224, 'name' => 'PORTUGAL', 'tax_haven_code' => 24, 'tax_haven_name' => 'ISLAS AZORES', 'created_at' => Carbon::now()],
            ['code' => 224, 'name' => 'PORTUGAL', 'tax_haven_code' => 41, 'tax_haven_name' => 'MADEIRA (Territorio de Portugal)', 'created_at' => Carbon::now()],
            ['code' => 225, 'name' => 'RUMANIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 226, 'name' => 'SUECIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 227, 'name' => 'SUIZA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 228, 'name' => 'CANARIAS  ISLAS', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 229, 'name' => 'UCRANIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 230, 'name' => 'RUSIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 231, 'name' => 'YUGOSLAVIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 233, 'name' => 'ANDORRA', 'tax_haven_code' => 52, 'tax_haven_name' => 'PRINCIPADO DEL VALLE DE ANDORRA', 'created_at' => Carbon::now()],
            ['code' => 234, 'name' => 'LIECHTENSTEIN', 'tax_haven_code' => 50, 'tax_haven_name' => 'PRINCIPADO DE LIECHTENSTEIN (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 235, 'name' => 'MONACO', 'tax_haven_code' => 51, 'tax_haven_name' => 'PRINCIPADO DE MÓNACO', 'created_at' => Carbon::now()],
            ['code' => 237, 'name' => 'SAN MARINO', 'tax_haven_code' => 81, 'tax_haven_name' => 'SERENÍSIMA REPÚBLICA DE SAN MARINO (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 238, 'name' => 'VATICANO (SANTA SEDE)', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 239, 'name' => 'GIBRALTAR', 'tax_haven_code' => 11, 'tax_haven_name' => 'COLONIA DE GIBRALTAR', 'created_at' => Carbon::now()],
            ['code' => 241, 'name' => 'BELARUS', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 242, 'name' => 'BOSNIA Y HERZEGOVINA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 243, 'name' => 'CROACIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 244, 'name' => 'ESLOVENIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 245, 'name' => 'ESTONIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 246, 'name' => 'GEORGIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 247, 'name' => 'GROENLANDIA', 'tax_haven_code' => 21, 'tax_haven_name' => 'GROENLANDIA', 'created_at' => Carbon::now()],
            ['code' => 248, 'name' => 'LETONIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 249, 'name' => 'LITUANIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 250, 'name' => 'MOLDOVA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 251, 'name' => 'MACEDONIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 252, 'name' => 'ESLOVAQUIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 253, 'name' => 'ISLAS FAROE', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 260, 'name' => 'FRENCH SOUTHERN TERRITORIES', 'tax_haven_code' => 49, 'tax_haven_name' => 'POLINESIA FRANCESA (Territorio de Ultramar de Francia)', 'created_at' => Carbon::now()],
            ['code' => 301, 'name' => 'AFGANISTAN', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 302, 'name' => 'ARABIA SAUDITA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 303, 'name' => 'MYANMAR (BURMA)', 'tax_haven_code' => 44, 'tax_haven_name' => 'MYANMAR (ex Birmania)', 'created_at' => Carbon::now()],
            ['code' => 304, 'name' => 'CAMBOYA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 306, 'name' => 'COREA NORTE', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 307, 'name' => 'TAIWAN (CHINA)', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 308, 'name' => 'FILIPINAS', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 309, 'name' => 'INDIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 310, 'name' => 'INDONESIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 311, 'name' => 'IRAK', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 312, 'name' => 'IRAN (REPUBLICA ISLAMICA)', 'tax_haven_code' => 33, 'tax_haven_name' => 'ISLA QESHM', 'created_at' => Carbon::now()],
            ['code' => 313, 'name' => 'ISRAEL', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 314, 'name' => 'JAPON', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 315, 'name' => 'JORDANIA', 'tax_haven_code' => 55, 'tax_haven_name' => 'REINO HACHEMITA DE JORDANIA', 'created_at' => Carbon::now()],
            ['code' => 316, 'name' => 'KUWAIT', 'tax_haven_code' => 16, 'tax_haven_name' => 'ESTADO DE KUWAIT (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 317, 'name' => 'LAOS, REP. POP. DEMOC.', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 318, 'name' => 'LIBANO', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 319, 'name' => 'MALASIA', 'tax_haven_code' => 39, 'tax_haven_name' => 'LABUAN', 'created_at' => Carbon::now()],
            ['code' => 321, 'name' => 'MONGOLIA (MANCHURIA)', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 322, 'name' => 'PAKISTAN', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 323, 'name' => 'SIRIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 325, 'name' => 'TAILANDIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 327, 'name' => 'BAHREIN', 'tax_haven_code' => 15, 'tax_haven_name' => 'ESTADO DE BAHREIN (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 328, 'name' => 'BANGLADESH', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 329, 'name' => 'BUTAN', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 330, 'name' => 'COREA DEL SUR', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 331, 'name' => 'CHINA POPULAR', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 332, 'name' => 'CHIPRE', 'tax_haven_code' => 60, 'tax_haven_name' => 'REPÚBLICA DE CHIPRE', 'created_at' => Carbon::now()],
            ['code' => 333, 'name' => 'EMIRATOS ARABES UNIDOS', 'tax_haven_code' => 18, 'tax_haven_name' => 'EMIRATOS ÁRABES UNIDOS (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 334, 'name' => 'QATAR', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 335, 'name' => 'MALDIVAS', 'tax_haven_code' => 64, 'tax_haven_name' => 'REPÚBLICA DE MALDIVAS (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 336, 'name' => 'NEPAL', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 337, 'name' => 'OMAN', 'tax_haven_code' => 82, 'tax_haven_name' => 'SULTANADO DE OMAN', 'created_at' => Carbon::now()],
            ['code' => 338, 'name' => 'SINGAPUR', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 339, 'name' => 'SRI LANKA (CEILAN)', 'tax_haven_code' => 74, 'tax_haven_name' => 'REPÚBLICA DEMOCRÁTICA SOCIALISTA DE SRI LANKA', 'created_at' => Carbon::now()],
            ['code' => 341, 'name' => 'VIETNAM', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 342, 'name' => 'YEMEN', 'tax_haven_code' => 73, 'tax_haven_name' => 'REPÚBLICA DEL YEMEN', 'created_at' => Carbon::now()],
            ['code' => 343, 'name' => 'ISLAS HEARD Y MCDONALD', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 344, 'name' => 'BRUNEI DARUSSALAM', 'tax_haven_code' => 9, 'tax_haven_name' => 'BRUNEI DARUSSALAM (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 346, 'name' => 'TURQUIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 347, 'name' => 'AZERBAIJAN', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 348, 'name' => 'KAZAJSTAN', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 349, 'name' => 'KIRGUIZISTAN', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 350, 'name' => 'TAJIKISTAN', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 351, 'name' => 'TURKMENISTAN', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 352, 'name' => 'UZBEKISTAN', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 353, 'name' => 'PALESTINA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 354, 'name' => 'HONG KONG', 'tax_haven_code' => 89, 'tax_haven_name' => 'HONG KONG', 'created_at' => Carbon::now()],
            ['code' => 355, 'name' => 'MACAO', 'tax_haven_code' => 40, 'tax_haven_name' => 'MACAO', 'created_at' => Carbon::now()],
            ['code' => 356, 'name' => 'ARMENIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 382, 'name' => 'MONTENEGRO', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 402, 'name' => 'BURKINA FASO', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 403, 'name' => 'ARGELIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 404, 'name' => 'BURUNDI', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 405, 'name' => 'CAMERUN', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 406, 'name' => 'CONGO', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 407, 'name' => 'ETIOPIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 408, 'name' => 'GAMBIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 409, 'name' => 'GUINEA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 410, 'name' => 'LIBERIA', 'tax_haven_code' => 63, 'tax_haven_name' => 'REPÚBLICA DE LIBERIA (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 412, 'name' => 'MADAGASCAR', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 413, 'name' => 'MALAWI', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 414, 'name' => 'MALI', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 415, 'name' => 'MARRUECOS', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 416, 'name' => 'MAURITANIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 417, 'name' => 'NIGERIA', 'tax_haven_code' => 45, 'tax_haven_name' => 'NIGERIA', 'created_at' => Carbon::now()],
            ['code' => 419, 'name' => 'ZIMBABWE (RHODESIA)', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 420, 'name' => 'SENEGAL', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 421, 'name' => 'SUDAN', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 422, 'name' => 'SUDAFRICA  (CISKEI)', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 423, 'name' => 'SIERRA LEONA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 425, 'name' => 'TANZANIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 426, 'name' => 'UGANDA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 427, 'name' => 'ZAMBIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 428, 'name' => 'ÅLAND ISLANDS', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 429, 'name' => 'BENIN', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 430, 'name' => 'BOTSWANA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 431, 'name' => 'REPUBLICA CENTROAFRICANA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 432, 'name' => 'COSTA DE MARFIL', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 433, 'name' => 'CHAD', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 434, 'name' => 'EGIPTO', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 435, 'name' => 'GABON', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 436, 'name' => 'GHANA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 437, 'name' => 'GUINEA-BISSAU', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 438, 'name' => 'GUINEA ECUATORIAL', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 439, 'name' => 'KENIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 440, 'name' => 'LESOTHO', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 441, 'name' => 'MAURICIO', 'tax_haven_code' => 66, 'tax_haven_name' => 'REPÚBLICA DE MAURICIO', 'created_at' => Carbon::now()],
            ['code' => 442, 'name' => 'MOZAMBIQUE', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 443, 'name' => 'MAYOTTE', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 444, 'name' => 'NIGER', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 445, 'name' => 'RWANDA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 446, 'name' => 'SEYCHELLES', 'tax_haven_code' => 69, 'tax_haven_name' => 'REPÚBLICA DE SEYCHELLES (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 447, 'name' => 'SAHARA OCCIDENTAL', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 448, 'name' => 'SOMALIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 449, 'name' => 'SANTO TOME Y PRINCIPE', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 450, 'name' => 'SWAZILANDIA', 'tax_haven_code' => 53, 'tax_haven_name' => 'REINO DE SWAZILANDIA (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 451, 'name' => 'TOGO', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 452, 'name' => 'TUNEZ', 'tax_haven_code' => 71, 'tax_haven_name' => 'REPÚBLICA DE TÚNEZ', 'created_at' => Carbon::now()],
            ['code' => 453, 'name' => 'ZAIRE', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 454, 'name' => 'ANGOLA', 'tax_haven_code' => 58, 'tax_haven_name' => 'REPÚBLICA DE ANGOLA', 'created_at' => Carbon::now()],
            ['code' => 456, 'name' => 'CABO VERDE', 'tax_haven_code' => 59, 'tax_haven_name' => 'REPÚBLICA DE CABO VERDE (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 458, 'name' => 'COMORAS', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 459, 'name' => 'DJIBOUTI', 'tax_haven_code' => 61, 'tax_haven_name' => 'REPÚBLICA DE DJIBOUTI (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 460, 'name' => 'NAMIBIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 463, 'name' => 'ERITREA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 464, 'name' => 'MOROCCO', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 465, 'name' => 'REUNION', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 466, 'name' => 'SANTA ELENA', 'tax_haven_code' => 23, 'tax_haven_name' => 'ISLA DE ASCENSIÓN', 'created_at' => Carbon::now()],
            ['code' => 466, 'name' => 'SANTA ELENA', 'tax_haven_code' => 78, 'tax_haven_name' => 'SANTA ELENA', 'created_at' => Carbon::now()],
            ['code' => 466, 'name' => 'SANTA ELENA', 'tax_haven_code' => 84, 'tax_haven_name' => 'TRISTAN DA CUNHA (SH Saint Helena)', 'created_at' => Carbon::now()],
            ['code' => 499, 'name' => 'JERSEY', 'tax_haven_code' => 88, 'tax_haven_name' => 'ISLAS DEL CANAL (Jersey)', 'created_at' => Carbon::now()],
            ['code' => 501, 'name' => 'AUSTRALIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 503, 'name' => 'NUEVA ZELANDA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 504, 'name' => 'SAMOA OCCIDENTAL', 'tax_haven_code' => 76, 'tax_haven_name' => 'SAMOA OCCIDENTAL', 'created_at' => Carbon::now()],
            ['code' => 506, 'name' => 'FIJI', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 507, 'name' => 'PAPUA NUEVA GUINEA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 508, 'name' => 'TONGA', 'tax_haven_code' => 54, 'tax_haven_name' => 'REINO DE TONGA (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 509, 'name' => 'PALAO  (BELAU)  ISLAS', 'tax_haven_code' => 47, 'tax_haven_name' => 'PALAU', 'created_at' => Carbon::now()],
            ['code' => 510, 'name' => 'KIRIBATI', 'tax_haven_code' => 38, 'tax_haven_name' => 'KIRIBATI', 'created_at' => Carbon::now()],
            ['code' => 511, 'name' => 'MARSHALL ISLAS', 'tax_haven_code' => 62, 'tax_haven_name' => 'REPÚBLICA DE LAS ISLAS MARSHALL (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 512, 'name' => 'MICRONESIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 513, 'name' => 'NAURU', 'tax_haven_code' => 67, 'tax_haven_name' => 'REPÚBLICA DE NAURU (Estado independiente)', 'created_at' => Carbon::now()],
            ['code' => 514, 'name' => 'SALOMON  ISLAS', 'tax_haven_code' => 34, 'tax_haven_name' => 'ISLAS SALOMÓN', 'created_at' => Carbon::now()],
            ['code' => 515, 'name' => 'TUVALU', 'tax_haven_code' => 85, 'tax_haven_name' => 'TUVALU', 'created_at' => Carbon::now()],
            ['code' => 516, 'name' => 'VANUATU', 'tax_haven_code' => 72, 'tax_haven_name' => 'REPÚBLICA DE VANUATU', 'created_at' => Carbon::now()],
            ['code' => 517, 'name' => 'GUAM', 'tax_haven_code' => 22, 'tax_haven_name' => 'GUAM (Territorio no autónomo de los EEUU)', 'created_at' => Carbon::now()],
            ['code' => 518, 'name' => 'ISLAS COCOS (KEELING)', 'tax_haven_code' => 27, 'tax_haven_name' => 'ISLA DE COCOS O KEELING', 'created_at' => Carbon::now()],
            ['code' => 519, 'name' => 'ISLAS COOK', 'tax_haven_code' => 28, 'tax_haven_name' => 'ISLA DE COOK (Territorio autónomo asociado a Nueva Zelanda)', 'created_at' => Carbon::now()],
            ['code' => 520, 'name' => 'ISLAS NAVIDAD', 'tax_haven_code' => 26, 'tax_haven_name' => 'ISLAS CHRISTMAS', 'created_at' => Carbon::now()],
            ['code' => 521, 'name' => 'MIDWAY ISLAS', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 522, 'name' => 'NIUE ISLA', 'tax_haven_code' => 46, 'tax_haven_name' => 'NIUE', 'created_at' => Carbon::now()],
            ['code' => 523, 'name' => 'NORFOLK ISLA', 'tax_haven_code' => 30, 'tax_haven_name' => 'ISLA DE NORFOLK', 'created_at' => Carbon::now()],
            ['code' => 524, 'name' => 'NUEVA  CALEDONIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 525, 'name' => 'PITCAIRN, ISLA', 'tax_haven_code' => 48, 'tax_haven_name' => 'PITCAIRN', 'created_at' => Carbon::now()],
            ['code' => 526, 'name' => 'POLINESIA FRANCESA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 529, 'name' => 'TIMOR DEL ESTE', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 530, 'name' => 'TOKELAI', 'tax_haven_code' => 83, 'tax_haven_name' => 'TOKELAU', 'created_at' => Carbon::now()],
            ['code' => 531, 'name' => 'WAKE ISLA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 532, 'name' => 'WALLIS Y FUTUNA, ISLAS', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 534, 'name' => 'SINT MAARTEN (DUTCH PART)', 'tax_haven_code' => 80, 'tax_haven_name' => 'SAN MARTÍN', 'created_at' => Carbon::now()],
            ['code' => 590, 'name' => 'SAINT BARTHELEMY', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 593, 'name' => 'ECUADOR', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 594, 'name' => 'AGUAS INTERNACIONALES', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 595, 'name' => 'ALTO VOLTA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 596, 'name' => 'BIELORRUSIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 597, 'name' => 'COTE DÍVOIRE', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 598, 'name' => 'CYPRUS', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 599, 'name' => 'REPUBLICA CHECA', 'tax_haven_code' => 86, 'tax_haven_name' => 'ZONA LIBRE DE OSTRAVA', 'created_at' => Carbon::now()],
            ['code' => 600, 'name' => 'FALKLAND ISLANDS', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 601, 'name' => 'LATVIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 602, 'name' => 'LIBIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 603, 'name' => 'NORTHERN MARIANA ISL', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 604, 'name' => 'ST. PIERRE AND MIQUE', 'tax_haven_code' => 31, 'tax_haven_name' => 'ISLA DE SAN PEDRO Y MIGUELÓN', 'created_at' => Carbon::now()],
            ['code' => 605, 'name' => 'SYRIAN ARAB REPUBLIC', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 606, 'name' => 'TERRITORIO ANTARTICO BRITANICO', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 607, 'name' => 'TERRITORIO BRITANICO OCEANO IN', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 688, 'name' => 'SERBIA', 'tax_haven_code' => null, 'tax_haven_name' => null, 'created_at' => Carbon::now()],
            ['code' => 831, 'name' => 'GUERNSEY', 'tax_haven_code' => 32, 'tax_haven_name' => 'ISLAS DEL CANAL (Guernesey, Alderney, Isla de Great Stark, Herm, Little Sark, Brechou, Jethou, Lihou)', 'created_at' => Carbon::now()],
            ['code' => 833, 'name' => 'ISLE OF MAN', 'tax_haven_code' => 29, 'tax_haven_name' => 'ISLA DE MAN (Territorio del Reino Unido)', 'created_at' => Carbon::now()],
        ]);
    }
}
